import 'package:flutter/material.dart';
import '../models/job.dart';
import '../services/api_service.dart';

class CreateJobScreen extends StatefulWidget {
  @override
  _CreateJobScreenState createState() => _CreateJobScreenState();
}

class _CreateJobScreenState extends State<CreateJobScreen> {
  final _formKey = GlobalKey<FormState>();
  String title = '';
  String company = '';
  String description = '';
  String location = '';
  String salary = '';
  String requirements = '';

  void _submitForm() {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      ApiService().createJob(Job(
        id: '', // Assuming ID will be generated by the backend
        title: title,
        company: company,
        description: description,
        location: location,
        salary: salary,
        requirements: requirements,
      ));
      Navigator.pop(context); // Navigate back after submission
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Create Job Posting')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                decoration: InputDecoration(labelText: 'Job Title'),
                validator: (value) {
                  if (value!.isEmpty) {
                    return 'Please enter job title';
                  }
                  return null;
                },
                onSaved: (value) {
                  title = value!;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Company Name'),
                validator: (value) {
                  if (value!.isEmpty) {
                    return 'Please enter company name';
                  }
                  return null;
                },
                onSaved: (value) {
                  company = value!;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Job Description'),
                validator: (value) {
                  if (value!.isEmpty) {
                    return 'Please enter job description';
                  }
                  return null;
                },
                onSaved: (value) {
                  description = value!;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Location'),
                validator: (value) {
                  if (value!.isEmpty) {
                    return 'Please enter job location';
                  }
                  return null;
                },
                onSaved: (value) {
                  location = value!;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Salary'),
                validator: (value) {
                  if (value!.isEmpty) {
                    return 'Please enter salary';
                  }
                  return null;
                },
                onSaved: (value) {
                  salary = value!;
                },
              ),
              TextFormField(
                decoration: InputDecoration(labelText: 'Requirements'),
                validator: (value) {
                  if (value!.isEmpty) {
                    return 'Please enter job requirements';
                  }
                  return null;
                },
                onSaved: (value) {
                  requirements = value!;
                },
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: _submitForm,
                child: Text('Create Job'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
